# Answers generated by Claude (this model), reading ONLY the retrieved context
# for each condition, mirroring the "Context:...\n\nQuestion:...\nAnswer concisely:"
# prompt used in run_c0.py/run_c1.py/run_c6.py. No outside lookup of gold answers
# was used to write these -- these reflect genuine best-effort answers given
# what each retrieval condition actually surfaced.

ANSWERS = {
0: {  # AmEx gross margin driver, domain-relevant
 "C0": "The retrieved context (investment securities and capital-ratio disclosures) does not address gross margin. American Express is a payments and financial services company, not a manufacturer or retailer, so it does not report cost of goods sold and gross margin is not a metric it uses; performance is instead measured through revenue, net income, and capital ratios.",
 "C1": "The retrieved context covers investment securities accounting and does not mention gross margin. As a financial services company, American Express does not have a cost-of-goods-sold structure, so gross margin is not a relevant or reported metric for it.",
 "C6": "The retrieved context (banking regulation, deferred compensation, and tax matters) does not discuss gross margin. Gross margin is not a meaningful metric for American Express because it is a financial services/payments company without a traditional cost-of-goods-sold structure.",
},
1: {  # Best Buy gross margin consistency, domain-relevant
 "C0": "Yes, gross margins have been reasonably consistent: gross profit as a percent of revenue was 22.4% in FY2021, 22.5% in FY2022, and 21.4% in FY2023 -- a decline of about 1.1 percentage points from FY2022 to FY2023, within the roughly 2% threshold.",
 "C1": "Yes. Gross profit as a percent of revenue was 22.4% (FY2021), 22.5% (FY2022), and 21.4% (FY2023), a year-over-year change of about 1.1 percentage points from FY2022 to FY2023, so margins have been fairly consistent.",
 "C6": "The retrieved context (employee assistance programs and SEC filing/reporting boilerplate) does not contain gross margin figures for Best Buy, so consistency cannot be confirmed from this context.",
},
2: {  # Corning effective tax rate change, domain-relevant
 "C0": "The retrieved context shows the reconciliation of unrecognized tax benefits but not the effective tax rate reconciliation itself, so the change in effective tax rate cannot be determined from this context.",
 "C1": "The retrieved context discusses unrecognized tax benefits and audit exposure but does not show the effective tax rate for FY2021 or FY2022, so the change cannot be computed from this context.",
 "C6": "The effective tax rate increased from 20.2% in FY2021 to 22.9% in FY2022, an increase of about 2.7 percentage points, per the statutory-to-effective tax rate reconciliation table.",
},
3: {  # AMD quick ratio, domain-relevant
 "C0": "The retrieved context (product lines and sales channels) does not contain balance sheet figures, so the quick ratio cannot be computed from this context.",
 "C1": "The retrieved context describes AMD's GPU product lines, not balance sheet data, so cash, receivables, and current liabilities needed for the quick ratio are not available here.",
 "C6": "The retrieved context covers tax carryforwards and an executive certification, not balance sheet line items, so the quick ratio cannot be determined from this context.",
},
4: {  # Best Buy cash flow source, domain-relevant
 "C0": "Operating activities generated the most cash in FY2023: $1,824 million provided by operations, versus $962 million used in investing activities and $1,806 million used in financing activities.",
 "C1": "Operating activities: cash provided by operating activities was $1,824 million in FY2023, compared to cash used in investing activities of $962 million and cash used in financing activities of $1,806 million, so operations brought in the most cash.",
 "C6": "Operating activities generated the most cash ($1,824 million), compared to cash used in investing (-$962 million) and financing (-$1,806 million) activities.",
},
5: {  # AWK dividends paid, metrics-generated
 "C0": "American Water Works paid $389 million in cash dividends during 2020, i.e. approximately $0.39 billion.",
 "C1": "The retrieved context shows components of operating cash flow (net income, depreciation, working capital changes) but does not show the specific cash dividends paid line, so the FY2020 dividend amount cannot be determined from this context.",
 "C6": "The retrieved context discusses use of capital resources (including paying dividends) in general terms but does not give the specific FY2020 cash dividends figure, so the amount cannot be determined from this context.",
},
6: {  # PepsiCo EBITDA - capex, metrics-generated
 "C0": "The context shows net income ($8,978M) and depreciation & amortization ($2,763M) from the cash flow statement, and capital spending ($5,207M) from the free cash flow reconciliation, but does not show operating income as a separate line item. Since the question specifically defines unadjusted EBITDA using operating income (not net income), this cannot be precisely computed from the given context.",
 "C1": "The context shows capital spending of $5,207 million (FY2022) in the free cash flow reconciliation, but does not show operating income or depreciation and amortization, so unadjusted EBITDA less capex cannot be computed from this context alone.",
 "C6": "The retrieved context (accumulated other comprehensive loss reclassifications and lease disclosures) does not contain operating income, D&A, or capex figures, so this cannot be computed from this context.",
},
7: {  # 3M net PP&E, metrics-generated
 "C0": "The retrieved context covers long-term debt and borrowings, not balance sheet property/plant/equipment figures, so net PP&E cannot be determined from this context.",
 "C1": "The retrieved context is a long-term debt schedule, not the balance sheet, so it does not contain the net PP&E figure needed to answer this question.",
 "C6": "The retrieved context covers revenue recognition and segment net sales, not balance sheet PP&E, so net PP&E cannot be determined from this context.",
},
8: {  # 3M capex, metrics-generated
 "C0": "The retrieved context covers long-term debt schedules, not the cash flow statement's investing activities section, so the FY2018 capital expenditure amount cannot be determined from this context.",
 "C1": "The retrieved context is a debt maturity schedule, not the cash flow statement, so it does not contain the capital expenditure figure requested.",
 "C6": "The retrieved context discusses goodwill impairment testing and a dividend declaration, not the cash flow statement, so capital expenditure cannot be determined from this context.",
},
9: {  # JPM VaR YoY, novel-generated
 "C0": "Yes, it decreased. Average total VaR decreased by $7 million for the three months ended June 30, 2023 compared with the same period in the prior year (Q2 2022), driven mainly by risk reductions in Credit Portfolio VaR and fixed income.",
 "C1": "Yes. It decreased: Total VaR averaged $47 million in Q2 2023 versus $54 million in Q2 2022, a year-over-year decrease of $7 million, driven by reductions in Credit Portfolio VaR and fixed income risk.",
 "C6": "Yes. It decreased. Average total VaR decreased by $7 million for the three months ended June 30, 2023 versus the same period a year earlier, driven predominantly by risk reductions in Credit Portfolio VaR and fixed income.",
},
10: {  # PepsiCo credit agreement increase, novel-generated
 "C0": "PepsiCo increased its unsecured five year revolving credit agreement by $400,000,000 -- from $3,800,000,000 (2022 Five Year Credit Agreement, terminated) to $4,200,000,000 (2023 Five Year Credit Agreement), effective May 26, 2023.",
 "C1": "PepsiCo entered into a new $4,200,000,000 five year unsecured revolving credit agreement on May 26, 2023, replacing the prior $3,800,000,000 facility -- an increase of $400,000,000.",
 "C6": "The increase was $400,000,000: PepsiCo terminated its $3,800,000,000 five year unsecured revolving credit agreement and replaced it with a new $4,200,000,000 five year unsecured revolving credit agreement on May 26, 2023.",
},
11: {  # AmEx card member retention, novel-generated
 "C0": "The context does not report a specific retention metric, but it describes continued investment in the Delta cobrand partnership, Membership Rewards, and a spend-centric model designed to keep Card Members engaged, suggesting continuity rather than attrition. On balance, yes, but this is inferred rather than directly stated.",
 "C1": "The context does not give an explicit card member retention figure for 2022; it mentions colleague (employee) retention, not card member retention specifically, so this cannot be confirmed directly from this context.",
 "C6": "The context does not state a retention rate, but it describes ongoing investment in the cobrand partnership and loyalty/rewards programs aimed at keeping Card Members engaged, which suggests retention was maintained, though this is inferred rather than a stated figure.",
},
12: {  # Amcor real sales growth, novel-generated
 "C0": "The retrieved context explains how Amcor computes constant-currency and comparable measures conceptually, but does not show the actual growth percentages, so the real (comparable constant currency) sales change cannot be determined from this context.",
 "C1": "For the twelve months ended June 30, 2023 vs FY2022, the Comparable Constant Currency Growth was approximately 0% (flat) for the total company -- reported growth of 1%, minus an unfavorable FX impact of about 3%, plus raw material pass-through of about 5%, and a roughly 1% comparability adjustment, netting to flat underlying growth.",
 "C6": "Net sales on a comparable constant currency basis were in line with the prior year (i.e., approximately flat), reflecting roughly 3% price/mix benefit offset by roughly 3% lower volumes.",
},
13: {  # Foot Locker new CEO experience, novel-generated
 "C0": "Yes. The incoming CEO, Mary Dillon, previously served as CEO of Ulta Beauty, a large omni-channel retailer, which is a comparable large-scale brick-and-mortar-plus-digital retail business to Foot Locker.",
 "C1": "Yes, the new CEO (Mary Dillon) has over 35 years of experience leading consumer-driven businesses and most recently served as CEO of Ulta Beauty, a comparable large omni-channel retailer.",
 "C6": "Yes. Dillon most recently served as CEO of Ulta Beauty for eight years, guiding it as a leading omni-channel retailer -- directly comparable retail leadership experience to what Foot Locker requires.",
},
}
